//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrcClientDemoCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRCConnection
    {
        public int Id { get; set; }
        public bool DefaultServer { get; set; }
        public string ServerAddress { get; set; }
        public string Channel { get; set; }
        public string User { get; set; }
        public string OAuth { get; set; }
        public int Port { get; set; }
    }
}
