//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrcClientDemoCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipLevel
    {
        public int Id { get; set; }
        public short MembershipLevel1 { get; set; }
        public double Multiplier { get; set; }
        public string MembershipLevelName { get; set; }
    }
}
