//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrcClientDemoCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string Greeting { get; set; }
        public string GreetingPosition { get; set; }
        public string BalanceCommand { get; set; }
        public string GambleCommand { get; set; }
        public string TradeCommand { get; set; }
        public double PointsPerTick { get; set; }
        public int TickMinutes { get; set; }
        public bool EarnPoints { get; set; }
    }
}
