//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrcClientDemoCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransaction
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public double Amount { get; set; }
    }
}
